/** Real Chromium interaction against the offline, real-assembly candidate fixture (not Desktop/IPC acceptance). */
import path from 'node:path';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..'),out=path.join(root,'build/source-ui-browser');
const require=createRequire(path.join(root,'../buildr/package.json'));
const {chromium}=require('playwright-core');
const binary=process.env.BUILDR_DSH_SOURCE_UI_CHROMIUM;
if(binary===undefined||!path.isAbsolute(binary))throw Error('BUILDR_DSH_SOURCE_UI_CHROMIUM must name an already prepared absolute Chromium executable.');
await fs.access(binary,fs.constants.X_OK);
const browser=await chromium.launch({headless:true,executablePath:binary});
try{
 const context=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1000}});
 await context.route(/^https?:/,route=>route.abort());
 const page=await context.newPage(),errors:string[]=[];
 page.on('pageerror',error=>errors.push(error.stack??error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
 const countRequests=()=>page.evaluate(()=>window.sourceFixture.requests.length);
 const settlePaint=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const selectCall=async(callId:string)=>{
  const recordId=await page.evaluate(id=>window.sourceFixture.records.find(record=>record.callId===id)?.recordId,callId);
  assert.equal(typeof recordId,'string','Fixture call must retain its durable producer record');
  const selector=JSON.stringify(recordId),button=page.locator(`[data-buildr-record-selector=${selector}], [data-buildr-record-selector=${selector}]`);
  await button.waitFor();await button.click();
 };
 const sourceView=()=>page.getByRole('searchbox',{name:'搜索 Buildr 对象'}).locator('xpath=ancestor::main[1]');
 const details=()=>sourceView().getByRole('region',{name:'参与详情',exact:true});
 const shownIds=()=>page.locator('[data-buildr-record-selector]').evaluateAll(elements=>elements.map(element=>element.getAttribute('data-buildr-record-selector')??element.getAttribute('data-buildr-record-selector')));
 const assertOriginalOrder=async()=>{const shown=await shownIds(),original=await page.evaluate(()=>window.sourceFixture.records.map(record=>record.recordId));assert.deepEqual(shown,original.filter(id=>shown.includes(id)),'Local source state and search preserve producer record order');return shown;};
 const closedGeometry=async()=>{
  assert.equal(await details().count(),0,'A closed view has no retained detail region');assert.equal(await page.locator('[data-content-view]').count(),0);
  assert.equal(await sourceView().getAttribute('data-details-open'),'false');
  const first=page.locator('[data-buildr-record-selector]').first();
  const box=await first.locator('xpath=parent::*').evaluate(element=>{const view=element.closest('main');if(view===null)throw Error('Missing source viewport');const style=getComputedStyle(view);return {listWidth:element.getBoundingClientRect().width,availableWidth:view.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)};});
  assert.ok(box.listWidth>=box.availableWidth-2,'Closed details return the entire available width to the record list: '+JSON.stringify(box));return box;
 };
 await page.goto(pathToFileURL(path.join(out,'index.html')).href);
 try{await page.waitForFunction(()=>document.documentElement.dataset.fixtureReady==='true'||document.documentElement.dataset.fixtureError!==undefined);}catch(error){console.error('Browser startup errors:',JSON.stringify(errors));console.error('Fixture startup state:',await page.locator('html').evaluate(element=>element.outerHTML.slice(0,300)));throw error;}
 assert.equal(await page.locator('html').getAttribute('data-fixture-error'),null);
 const table=page.locator('table');await table.waitFor();await page.waitForFunction(()=>document.querySelectorAll('col').length===3);assert.equal(await page.locator('col').count(),3);
 await settlePaint();assert.equal(await countRequests(),0,'Opening the original trajectory must not query every row');
 const search=page.getByRole('searchbox',{name:'搜索轨迹'});
 await page.getByRole('button',{name:'收起所有轮次',exact:true}).click();await page.getByRole('button',{name:'展开所有轮次',exact:true}).click();
 await search.fill('AGENTS.md');await search.press('Enter');await page.getByRole('row',{name:/read_file/}).first().click();
 await page.locator('[data-content-view="observed"]').waitFor();
 await page.getByText('此处仅展示原事件保留的当次片段，不代表完整方法内容。',{exact:true}).waitFor();
 await page.locator('[data-content-view="observed"]').filter({hasText:'This is the method text retained in the original event.'}).waitFor();
 assert.equal(await page.locator('[data-content-view="observed"]').getAttribute('data-content-format'),'markdown');
 await page.getByRole('heading',{name:'Recorded Buildr rule',exact:true}).waitFor();
 await page.getByRole('button',{name:'原文',exact:true}).click();
 const rawMethod=await page.locator('[data-content-format="raw"] pre').textContent();assert.ok(rawMethod?.startsWith('# Recorded Buildr rule\n')&&rawMethod.endsWith('SYNTHETIC_BUILDR_METHOD_END'),'Original text retains the captured Markdown fragment verbatim');
 await page.getByRole('button',{name:'预览',exact:true}).click();assert.equal(await page.locator('[data-content-view="observed"]').getAttribute('data-content-format'),'markdown');
 assert.equal(await page.getByRole('button',{name:'当前内容',exact:true}).count(),0,'The recorded-event viewer has no current-file mode');
 assert.equal(await page.locator('[data-buildr-object-selector]').count(),0,'A single method opens directly without a redundant object picker');
 assert.equal(await countRequests(),1,'Only the selected method row is queried');
 const sourceRecordId=await page.evaluate(()=>window.sourceFixture.records.find(record=>record.callId==='fixture-read-call')?.recordId);
 assert.equal(typeof sourceRecordId,'string');
 const sourceSummary=page.locator(`td[data-trajectory-column] [data-buildr-record-id=${JSON.stringify(sourceRecordId)}]`);
 await sourceSummary.waitFor();
 const sourceColumnLines=await sourceSummary.locator(':scope > span').allTextContents();
 assert.deepEqual(sourceColumnLines,['Buildr（片段）','内容读取'],'The 112 px source cell keeps two short, legible lines');
 const sourceColumnTitle=await sourceSummary.getAttribute('title');
 assert.ok(sourceColumnTitle?.includes('已记录来源'),'The recorded source remains in the tooltip');
 assert.ok(sourceColumnTitle?.includes('Buildr 核心规则')&&sourceColumnTitle.includes('混合来源'),'The compact cell must retain full relation and fragment facts');
 assert.equal(await sourceSummary.getAttribute('aria-label'),sourceColumnTitle,'The full source meaning is also accessible without hover');
 const sourceColumnGeometry=await sourceSummary.evaluate(element=>{const cell=element.closest('td');if(cell===null)throw Error('Source summary has no original table cell');const box=cell.getBoundingClientRect();return {cell:{left:box.left,right:box.right,top:box.top,bottom:box.bottom,width:box.width},lines:[...element.children].map(line=>{const rect=line.getBoundingClientRect(),style=getComputedStyle(line),range=document.createRange();range.selectNodeContents(line);const textBox=range.getBoundingClientRect();return {text:line.textContent,left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom,clientWidth:line.clientWidth,scrollWidth:line.scrollWidth,textBounds:{left:textBox.left,right:textBox.right,width:textBox.width},fontSize:style.fontSize,fontFamily:style.fontFamily,overflowX:style.overflowX,textOverflow:style.textOverflow};})};});
 for(const line of sourceColumnGeometry.lines){assert.ok(line.left>=sourceColumnGeometry.cell.left-1&&line.right<=sourceColumnGeometry.cell.right+1,'Each source line fits the physical source column: '+JSON.stringify(sourceColumnGeometry));assert.ok(line.top>=sourceColumnGeometry.cell.top-1&&line.bottom<=sourceColumnGeometry.cell.bottom+1,'The two lines are not clipped vertically: '+JSON.stringify(sourceColumnGeometry));assert.ok(line.scrollWidth<=line.clientWidth+1,'The short source line is fully readable without ellipsis: '+JSON.stringify(sourceColumnGeometry));}
 const hideContent=page.getByRole('button',{name:'收起正文',exact:true});await hideContent.focus();await page.keyboard.press('Space');assert.equal(await page.locator('[data-content-view]').count(),0);
 const showContent=page.getByRole('button',{name:'查看正文',exact:true});await showContent.focus();await page.keyboard.press('Enter');await page.locator('[data-content-view="observed"]').waitFor();
 await page.screenshot({path:path.join(out,'wide-original-inspector.png'),fullPage:true});
 await page.getByRole('tab',{name:'参数',exact:true}).click();await page.getByText('/fixture/AGENTS.md',{exact:false}).first().waitFor();
 await page.getByRole('tab',{name:'结果',exact:true}).click();await page.getByText('Original preserved tool output',{exact:false}).first().waitFor();
 await page.getByRole('tab',{name:'Schema',exact:true}).click();await page.getByText('Read-only external fixture operation',{exact:false}).first().waitFor();
 await page.getByRole('tab',{name:'计时',exact:true}).click();await page.getByText(/^200\s*毫秒$/).waitFor();await page.screenshot({path:path.join(out,'wide-tool-timing.png'),fullPage:true});
 await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await search.fill('');await search.press('Enter');await page.waitForFunction(()=>document.querySelectorAll('tr[data-record-index]').length>1);const totalRows=Number(await table.getAttribute('aria-rowcount')),renderedRows=await page.locator('tr[data-record-index]').count();assert.ok(renderedRows<totalRows);
 await search.fill('Loaded window record 80');await search.press('Enter');await page.getByRole('row',{name:/Loaded window record 80/}).waitFor();assert.equal(await page.locator('tr[data-record-index]').count(),1);
 await page.screenshot({path:path.join(out,'wide-search.png'),fullPage:true});await search.fill('');await search.press('Enter');
 await page.getByRole('button',{name:'收起所有轮次'}).click();await page.getByRole('button',{name:'展开所有轮次'}).click();
 assert.equal(await countRequests(),1,'Original search, fold and timing do not trigger extra source reads');
 const beforeSource=await countRequests();await page.getByRole('button',{name:'Buildr 来源入口',exact:true}).click();await page.locator('[data-buildr-record-selector]').first().waitFor();await settlePaint();assert.equal(await countRequests(),beforeSource);
 assert.equal(await page.locator('[data-buildr-record-selector]').filter({hasText:'user-notes.md'}).count(),0,'Ordinary user materials stay out of the Buildr-marked list');
 const initialClosed=await closedGeometry(),initialOrder=await assertOriginalOrder();assert.equal(await page.locator('[data-buildr-candidate-selector]').count(),0);assert.equal(await page.evaluate(()=>window.sourceFixture.requests.some(request=>request.mode==='marker')),false,'The viewer never issues a marker query');
 await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();
 assert.equal(await page.locator('[data-buildr-object-selector]').count(),0);
 const confirmed=page.locator('[data-buildr-record-selector]').first();assert.match(await confirmed.locator('strong').innerText(),/Buildr 核心规则/);assert.doesNotMatch(await confirmed.locator('strong').innerText(),/workspace:fixture/);
 await confirmed.getByText('已读取',{exact:true}).waitFor();
 const confirmedTitle=await confirmed.getAttribute('title');assert.ok(confirmedTitle?.includes('已记录来源'),'The compact row preserves the recorded source on hover');assert.equal(await confirmed.getAttribute('aria-label'),confirmedTitle,'The same source meaning is available without hover');
 await page.screenshot({path:path.join(out,'wide-buildr-source.png'),fullPage:true});
 const sourceSearch=page.getByRole('searchbox',{name:'搜索 Buildr 对象'}),beforeSearch=await countRequests();
 await sourceSearch.fill('技能读取');const actionMatches=await assertOriginalOrder();assert.ok(actionMatches.length>=24,'Localized skill-reading actions can be searched');
 const coreId=await page.evaluate(()=>window.sourceFixture.records.find(record=>record.callId==='fixture-read-call')?.recordId);assert.ok(!actionMatches.includes(coreId));assert.equal(await countRequests(),beforeSearch,'Action search never asks the source service');
 await sourceSearch.fill('');const beforeSkillOrder=await assertOriginalOrder();
 await selectCall('fixture-skill-call');await page.getByText('Buildr method instructions for the selected skill.',{exact:false}).waitFor();await settlePaint();assert.deepEqual(await assertOriginalOrder(),beforeSkillOrder,'A newly checked skill stays in its original timeline position');
 const beforeNameSearch=await countRequests();await sourceSearch.fill('task-review');assert.equal((await shownIds()).length,1);assert.equal(await countRequests(),beforeNameSearch);await sourceSearch.fill('');
 const beforeCapabilities=await countRequests();await selectCall('fixture-capability-call');await details().getByText('查看任务 Fixture task',{exact:true}).waitFor();await details().getByText('执行成功',{exact:true}).waitFor();assert.equal(await details().getByText('作用对象: Fixture task',{exact:true}).count(),0,'The target is stated once in the action headline');assert.equal(await page.locator('[data-content-view]').count(),0);assert.equal(await page.getByText('Private user brief must not become Buildr method content.',{exact:false}).count(),0);
 await selectCall('fixture-failed-capability-call');await details().getByText('执行失败 · 退出码 1',{exact:true}).waitFor();await details().getByText('查看任务 Failed fixture task',{exact:true}).waitFor();assert.equal(await details().locator('[data-content-view]').count(),0,'A failed capability with none completeness never displays a user result body');assert.equal(await countRequests(),beforeCapabilities,'Body-free capability details consume the saved source and outcome locally');
 const beforeTargetSearch=await countRequests();await sourceSearch.fill('Fixture task');const targetMatches=await assertOriginalOrder();const capabilityIds=await page.evaluate(()=>window.sourceFixture.records.filter(record=>record.callId==='fixture-capability-call'||record.callId==='fixture-failed-capability-call').map(record=>record.recordId));assert.deepEqual(targetMatches,capabilityIds,'Both successful and failed bound calls match their necessary target references in original record order');assert.equal(await countRequests(),beforeTargetSearch,'Target-reference search is local');await sourceSearch.fill('');
 await selectCall('fixture-multi-call');await page.locator('[data-buildr-object-selector]').first().waitFor();assert.equal(await page.locator('[data-buildr-object-selector]').count(),2);await page.locator('[data-buildr-object-selector]').nth(1).click();await page.getByText('Second Buildr method content.',{exact:false}).waitFor();
 await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();
 const beforeCloseRequests=await countRequests(),beforeCloseOrder=await assertOriginalOrder();
 const recordList=page.locator('[data-buildr-record-selector]').first().locator('xpath=parent::*'),listHandle=await recordList.elementHandle();assert.ok(listHandle);
 const openListWidth=(await recordList.boundingBox())?.width;assert.ok(openListWidth);
 await recordList.evaluate(element=>{element.scrollTop=180;});const savedListScroll=await recordList.evaluate(element=>element.scrollTop);
 const recordAnchor=()=>recordList.evaluate(element=>{const list=element.getBoundingClientRect(),row=[...element.querySelectorAll('[data-buildr-record-selector]')].find(row=>{const box=row.getBoundingClientRect();return box.bottom>list.top+1&&box.top<list.bottom-1;});if(row===undefined)throw Error('Scrollable method window lost its visible record anchor');return {id:row.getAttribute('data-buildr-record-selector')??row.getAttribute('data-buildr-record-selector'),top:row.getBoundingClientRect().top-list.top};});
 await settlePaint();const savedRecordAnchor=await recordAnchor();
 await details().getByRole('button',{name:'关闭详情',exact:true}).click();await settlePaint();const afterClose=await closedGeometry();assert.ok(afterClose.listWidth>openListWidth+200,'Wide close materially restores the hidden right-pane space');
 assert.equal(await recordList.evaluate((element,previous)=>element===previous,listHandle),true,'Closing retains the same list DOM and its local state');const closedListScroll=await recordList.evaluate(element=>element.scrollTop),closedRecordAnchor=await recordAnchor();assert.equal(closedRecordAnchor.id,savedRecordAnchor.id,'Closing preserves the first visible record even when the wider list reflows its heading');assert.ok(Math.abs(closedRecordAnchor.top-savedRecordAnchor.top)<=1,'Closing preserves the visible record position through browser scroll anchoring');assert.deepEqual(await assertOriginalOrder(),beforeCloseOrder);assert.equal(await countRequests(),beforeCloseRequests);
 assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('data-buildr-record-selector')),savedRecordAnchor.id,'Closing returns focus to an actually visible record without reading again');
 await page.screenshot({path:path.join(out,'wide-buildr-closed-list.png'),fullPage:true});
 await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();assert.equal(await countRequests(),beforeCloseRequests,'Reopening selected cached content does not repeat its source request');
 await sourceSearch.fill('no-method-matches-for-focus');assert.equal((await shownIds()).length,0);await details().getByRole('button',{name:'关闭详情',exact:true}).click();await settlePaint();assert.equal(await details().count(),0);assert.equal(await page.locator('[data-content-view]').count(),0);assert.equal(await sourceView().getAttribute('data-details-open'),'false');assert.equal(await sourceSearch.evaluate(element=>document.activeElement===element),true,'With no visible record, closing returns focus to the search input');assert.equal(await countRequests(),beforeCloseRequests);
 await sourceSearch.fill('');await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();assert.equal(await countRequests(),beforeCloseRequests);
 await page.evaluate(()=>window.sourceFixture.armGate());await selectCall('fixture-method-0');await page.waitForFunction(()=>window.sourceFixture.gate.started);const lateRequests=await countRequests();await details().getByRole('button',{name:'关闭详情',exact:true}).click();await settlePaint();await closedGeometry();
 await page.evaluate(()=>window.sourceFixture.releaseGate());const lateId=await page.evaluate(()=>window.sourceFixture.records.find(record=>record.callId==='fixture-method-0')?.recordId);await page.locator(`[data-buildr-record-selector=${JSON.stringify(lateId)}]`).waitFor();await settlePaint();await closedGeometry();assert.equal(await countRequests(),lateRequests,'A completed late response updates the list/cache only');await assertOriginalOrder();
 await selectCall('fixture-method-0');await page.getByText('Buildr method instructions for the selected skill.',{exact:false}).waitFor();assert.equal(await countRequests(),lateRequests,'Reopening the late completed result uses its retained cache');await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();
 await page.evaluate(()=>document.body.setAttribute('data-ds-dark-theme',''));await page.screenshot({path:path.join(out,'wide-buildr-dark.png'),fullPage:true});await page.evaluate(()=>document.body.removeAttribute('data-ds-dark-theme'));
 await page.setViewportSize({width:420,height:900});await page.screenshot({path:path.join(out,'narrow-buildr-source.png'),fullPage:true});
 await page.getByRole('button',{name:'撤回来源消费者',exact:true}).click();await page.locator('[data-buildr-record-selector]').first().waitFor({state:'detached'});await page.evaluate(()=>window.sourceFixture.armGate());
 const beforeGate=await countRequests();await page.getByRole('button',{name:'Buildr 来源入口',exact:true}).click();await page.locator('[data-buildr-record-selector]').first().waitFor();await settlePaint();assert.equal(await countRequests(),beforeGate,'Reentry marks automatically but waits for an explicit content choice');
 await selectCall('fixture-read-call');await page.waitForFunction(()=>window.sourceFixture.gate.started);const requestsAtWithdrawal=await countRequests();
 await page.getByRole('button',{name:'撤回来源消费者',exact:true}).click();await page.locator('[data-buildr-record-selector]').first().waitFor({state:'detached'});await page.evaluate(async()=>{window.sourceFixture.releaseGate();await Promise.resolve();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});assert.equal(await countRequests(),requestsAtWithdrawal);assert.equal(await page.locator('[data-content-view]').count(),0);
 await page.getByRole('button',{name:'Buildr 来源入口',exact:true}).click();await page.locator('[data-buildr-record-selector]').first().waitFor();await settlePaint();assert.equal(await countRequests(),requestsAtWithdrawal);await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();assert.equal(await countRequests(),requestsAtWithdrawal+1);
 await page.getByRole('button',{name:'原轨迹入口',exact:true}).click();await table.waitFor();await page.screenshot({path:path.join(out,'narrow-original.png'),fullPage:true});
 await page.getByRole('button',{name:'卸载 Buildr 贡献',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('col').length===2);assert.equal(await page.locator('[data-buildr-object-id]').count(),0);
 await page.screenshot({path:path.join(out,'narrow-after-unload.png'),fullPage:true});
 await page.evaluate(()=>window.sourceFixture.mountDev());const beforeDev=await countRequests();await page.getByRole('button',{name:'Buildr 开发入口',exact:true}).click();await page.locator('[data-buildr-record-selector]').first().waitFor();await settlePaint();assert.equal(await countRequests(),beforeDev);await selectCall('fixture-read-call');await page.locator('[data-content-view="observed"]').waitFor();assert.equal(await page.locator('[data-buildr-object-selector]').count(),0);await page.screenshot({path:path.join(out,'narrow-development-source.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 assert.equal(await page.evaluate(()=>window.sourceFixture.requests.every(request=>request.mode==='content'&&request.record.eventSources===undefined)),true,'All Host requests are explicit original-content reads, never marker calls or copied source metadata');
 const inputs=JSON.parse(await fs.readFile(path.join(out,'inputs.json'),'utf8'));
 const summary={schemaVersion:'buildr.dsh-recorded-source-browser-result/v1',status:'passed',inputs,runtime:{node:process.execPath,chromium:binary},tier:'offline real-framework Chromium fixture with compiled Buildr Client artifacts',notDesktop:true,controlledRPC:true,hostComposerHeight:170,sourceColumn:{lines:sourceColumnLines,title:sourceColumnTitle,geometry:sourceColumnGeometry},viewports:[{width:1440,height:1000},{width:420,height:900}],keyboard:['Space hides recorded content','Enter shows recorded content'],preserved:['original Trajectory','original Inspector','tool Input','tool Output','tool Schema','tool Timing','search','fold'],virtualized:{totalRows,renderedRows},detailInteraction:{initialClosed,initialOrder,closedFullWidth:afterClose,listDOMAndVisibleRecordAnchorRetained:true,scroll:{savedListScroll,closedListScroll,savedRecordAnchor,closedRecordAnchor},focusRestored:true,filteredEmptyFocusReturnsToSearch:true,cachedReopenWithoutRequest:true,lateCompletionDoesNotReopen:true,producerOrderPreserved:true,localizedActionAndTargetSearchLocal:true},scope:{methods:['rule','skill','capability'],ordinaryUserReadExcluded:true,userBriefOnlyCapabilityTarget:true,singleObjectPickerHidden:true,multiObjectPickerCount:2,recordedMetadataOnly:true,recordedPartialShown:true,failedCapabilityNoneBody:true,currentModeAbsent:true,defaultRecordedBodyExpanded:true,defaultMarkdownPreview:true,rawUsesExactRecordedFragment:true,bodyFreeCapabilityDetailsUseNoRPC:true},queries:{markerRPCOnEntry:0,sourceRPCOnEntry:0,allRequestsExplicitContent:true,metadataAuthority:'persisted eventSources returned with the original loaded records',contentAuthority:'original event UTF-16 contentRefs',noCurrentSourceLookup:true},lateWindowRead:'withdrawn queued result does not restore old body; explicit reentry choice rereads',developmentVariant:'actual compiled development plugin applied',themes:['light','dark'],unloadColumns:[3,2],consoleErrors:errors};
 await fs.writeFile(path.join(out,'browser-result.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary));await context.close();
}finally{await browser.close();}
