import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import YAML from 'yaml';
import { resolveSourceRoot } from '../../workspace/module.ts';
import { normalizeProjectVerification, parseProjectVerification, validateProjectVerification } from '../domain/project-verification.ts';

const digest = (value: Buffer | string) => `sha256-${crypto.createHash('sha256').update(value).digest('hex')}`;
type ProjectVerificationFileMutations = Readonly<{
  atomicWriteFile(file: string, content: string): void;
}>;
function projectContext(runtime: any, targetRoot: string, projectCode: string) { const root = fs.realpathSync(path.resolve(targetRoot)); const project = runtime.readProjectRegistryPersistence(root).registry.projects[projectCode]; if (!project) throw Object.assign(new Error(`Project 未登记：${projectCode}。`), { code: 'project_verification_project_not_found', status: 404 }); const projectRoot = resolveSourceRoot(root, project.source); const services = Object.keys(runtime.readServiceRegistryPersistence?.(root, project, project.workspaceId)?.registry?.services || {}); return { root, project, projectRoot, services, file: path.join(projectRoot, 'verification.yml') }; }
function readCandidate(file: string, context: any) { const content = fs.readFileSync(file); const value = parseProjectVerification(content.toString('utf8'), file); return { declaration: normalizeProjectVerification(value, { projectCode: context.project.code || context.projectCode, services: context.services }), content }; }
function result(operation: string, status: string, project: string, values: any = {}) { return { schemaVersion: 'buildr.project-verification-result/v1', operation, status, project, path: values.path || null, identity: values.identity || null, declaration: values.declaration || null, errors: values.errors || [], effects: values.effects || [] }; }
function parseArgs(operation: string, args: string[]) { const allowed = operation === 'inspect' ? new Set(['--target', '--json']) : operation === 'validate' ? new Set(['--file', '--target', '--json']) : new Set(['--file', '--expected-identity', '--target', '--json']); const values = new Map<string, any>(); const positions: string[] = []; for (let index = 0; index < args.length; index += 1) { const arg = args[index]; if (!arg.startsWith('--')) { positions.push(arg); continue; } if (!allowed.has(arg)) throw new Error(`Unknown argument: ${arg}`); if (arg === '--json') values.set(arg, true); else { const value = args[++index]; if (!value || value.startsWith('--')) throw new Error(`Missing value for ${arg}`); values.set(arg, value); } } if (positions.length !== 1) throw new Error(`project verification ${operation} requires exactly one <project>.`); return { project: positions[0], targetRoot: path.resolve(values.get('--target') || process.cwd()), file: values.get('--file'), expectedIdentity: values.get('--expected-identity'), json: values.get('--json') === true }; }
export function registerProjectVerificationApplication(runtime: any, mutations: ProjectVerificationFileMutations) {
  function inspectProjectVerification(targetRoot: string, projectCode: string) { const context = projectContext(runtime, targetRoot, projectCode); if (!fs.existsSync(context.file)) return result('inspect', 'missing', projectCode, { path: path.relative(context.root, context.file).split(path.sep).join('/'), identity: 'absent' }); const content = fs.readFileSync(context.file); const value = parseProjectVerification(content.toString('utf8'), context.file); const errors = validateProjectVerification(value, { projectCode, services: context.services }); return result('inspect', errors.length ? 'invalid' : 'ready', projectCode, { path: path.relative(context.root, context.file).split(path.sep).join('/'), identity: digest(content), declaration: errors.length ? value : normalizeProjectVerification(value, { projectCode, services: context.services }), errors }); }
  function validateProjectVerificationCandidate(targetRoot: string, projectCode: string, file: string) { const context = projectContext(runtime, targetRoot, projectCode); const content = fs.readFileSync(path.resolve(file)); const value = parseProjectVerification(content.toString('utf8'), file); const errors = validateProjectVerification(value, { projectCode, services: context.services }); return result('validate', errors.length ? 'invalid' : 'ready', projectCode, { path: path.resolve(file), identity: digest(content), declaration: errors.length ? value : normalizeProjectVerification(value, { projectCode, services: context.services }), errors }); }
  function updateProjectVerification(targetRoot: string, projectCode: string, file: string, expectedIdentity: string) { const context = projectContext(runtime, targetRoot, projectCode); const current = fs.existsSync(context.file) ? digest(fs.readFileSync(context.file)) : 'absent'; if (current !== expectedIdentity) throw Object.assign(new Error(`verification.yml 已变化：${expectedIdentity} -> ${current}。`), { code: 'project_verification_conflict', status: 409 }); const candidate = validateProjectVerificationCandidate(targetRoot, projectCode, file); if (candidate.status !== 'ready') throw Object.assign(new Error(`verification.yml 候选无效：${candidate.errors.join('; ')}`), { code: 'project_verification_invalid', status: 400, details: { errors: candidate.errors } }); const serialized = YAML.stringify(candidate.declaration); mutations.atomicWriteFile(context.file, serialized); const content = fs.readFileSync(context.file); return result('update', 'updated', projectCode, { path: path.relative(context.root, context.file).split(path.sep).join('/'), identity: digest(content), declaration: parseProjectVerification(content.toString('utf8'), context.file), effects: [{ type: current === 'absent' ? 'created' : 'updated', path: path.relative(context.root, context.file).split(path.sep).join('/') }] }); }
  function projectVerificationCommand(operation: string, args: string[]) { const input = parseArgs(operation, args); const payload = operation === 'inspect' ? inspectProjectVerification(input.targetRoot, input.project) : operation === 'validate' ? validateProjectVerificationCandidate(input.targetRoot, input.project, input.file) : updateProjectVerification(input.targetRoot, input.project, input.file, input.expectedIdentity); if (input.json) process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`); else console.log(`Project ${payload.project} verification ${payload.status}.`); if (payload.status === 'invalid') process.exitCode = 1; return payload; }
  Object.assign(runtime, { inspectProjectVerification, validateProjectVerificationCandidate, updateProjectVerification, projectVerificationCommand }); return runtime;
}
