import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import YAML from 'yaml';

import { assetIntegrity } from '../../src/modules/agent-assets/infrastructure/component-source.ts';
import { skillDestinationRoot } from '../../src/modules/agent-assets/infrastructure/runtime/adapter-contract.ts';

const file = fileURLToPath(import.meta.url);
const serviceRoot = path.resolve(path.dirname(file), '../..');

function scenario() {
  const smokeRoot = process.env.BUILDR_SMOKE_ROOT;
  const workspace = process.env.BUILDR_SMOKE_WORKSPACE_ROOT;
  assert.ok(smokeRoot && workspace, 'Use the isolated Workspace smoke runner.');
  assert.equal(process.env.BUILDR_APP_DATA_DIR, path.join(smokeRoot, 'app-data'));
  assert.equal(process.env.BUILDR_PRODUCT_DATA_DIR, path.join(smokeRoot, 'product-data'));
  const userHome = path.join(smokeRoot, 'user');
  fs.mkdirSync(userHome, { recursive: true });
  // Only these child processes use the fixture home; the host installation is untouched.
  const env = { ...process.env, HOME: userHome, USERPROFILE: userHome };
  const entry = path.join(serviceRoot, 'bin/buildr.mjs');
  let step = 0;
  function progress(label: string) {
    process.stderr.write(`[archify-scenario] ${++step}: ${label}\n`);
  }
  function run(args: string[], expected = 0) {
    const label = args.slice(0, 3).join(' ');
    progress(`start ${label}`);
    const result = spawnSync(process.execPath, [entry, ...args], {
      cwd: serviceRoot, env, encoding: 'utf8', timeout: 60_000, maxBuffer: 8 * 1024 * 1024,
    });
    assert.equal(result.status, expected, `${args.join(' ')}\n${result.error?.message ?? ''}\n${result.stdout}\n${result.stderr}`);
    progress(`passed ${label}`);
    return result;
  }
  const target = ['--target', workspace];
  const source = path.join(serviceRoot, 'resources/workspace/skills/buildr/archify');
  const installed = path.join(workspace, 'skills/buildr/archify');
  const projected = path.join(workspace, '.agents/skills/archify');
  const definitionPath = path.join(serviceRoot, 'resources/workspace/components/buildr/archify/component.yml');
  const definition = YAML.parse(fs.readFileSync(definitionPath, 'utf8'));
  assert.equal(definition.upstream.version, '2.16.0');
  assert.equal(definition.integrity[0], `skills/buildr/archify=${assetIntegrity(source)}`);
  assert.equal(fs.existsSync(path.join(source, 'node_modules')), false);
  assert.match(fs.readFileSync(path.join(source, 'assets/archify/LICENSE'), 'utf8'), /MIT License/);

  run(['init', '--name', 'archify-component', '--profile', 'personal', ...target]);
  const listed = JSON.parse(run(['component', 'list', ...target, '--json']).stdout);
  const available = listed.components.find((item: { id: string }) => item.id === 'archify');
  assert.equal(available.status, 'available');
  assert.equal(available.required, false);
  assert.equal(available.defaultEnabled, false);
  assert.equal(fs.existsSync(installed), false);
  run(['sync', 'codex', ...target]);
  assert.equal(fs.existsSync(projected), false);

  // A same-name user installation remains externally owned throughout the lifecycle.
  const external = path.join(skillDestinationRoot('codex', 'user', workspace, { userHome }), 'skills/archify');
  fs.mkdirSync(external, { recursive: true });
  const externalBody = '---\nname: archify\ndescription: User-owned drawing tool.\n---\nUser-owned content.\n';
  fs.writeFileSync(path.join(external, 'SKILL.md'), externalBody);
  run(['component', 'install', 'archify', '--agent', 'codex', ...target]);
  assert.equal(fs.readFileSync(path.join(external, 'SKILL.md'), 'utf8'), externalBody);

  run(['component', 'install', 'archify', '--agent', 'codex', ...target]);
  assert.equal(assetIntegrity(installed), assetIntegrity(source));
  for (const relative of ['assets/archify/bin/archify.mjs', 'assets/archify/assets/template.html', 'assets/archify/LICENSE', 'assets/archify/skill-release.json']) {
    assert.deepEqual(fs.readFileSync(path.join(projected, relative)), fs.readFileSync(path.join(source, relative)));
  }
  assert.match(fs.readFileSync(path.join(projected, 'SKILL.md'), 'utf8'), /Generated by Buildr/);
  const before = assetIntegrity(projected);
  run(['sync', 'codex', ...target]);
  assert.equal(assetIntegrity(projected), before);
  const checked = JSON.parse(run(['component', 'check', 'archify', ...target, '--json']).stdout);
  assert.equal(checked.components[0].status, 'installed');
  assert.equal(checked.components[0].installedVersion, definition.version);

  // Exercise the installed renderer, templates and validators, not the product source.
  run(['project', 'create', 'example', ...target]);
  const graphRoot = path.join(workspace, 'projects/example/knowledge/archify');
  fs.mkdirSync(graphRoot, { recursive: true });
  const graph = path.join(graphRoot, 'example.json');
  const output = path.join(graphRoot, 'example.html');
  fs.copyFileSync(path.join(projected, 'assets/archify/examples/brand-aware-delivery.architecture.json'), graph);
  progress('start installed renderer');
  const delivered = spawnSync(process.execPath, [path.join(projected, 'assets/archify/bin/archify.mjs'),
    'deliver', 'architecture', graph, output, '--quality', 'showcase', '--json'], {
    cwd: projected, env, encoding: 'utf8', timeout: 60_000, maxBuffer: 4 * 1024 * 1024,
  });
  assert.equal(delivered.status, 0, `${delivered.error?.message ?? ''}\n${delivered.stdout}\n${delivered.stderr}`);
  progress('passed installed renderer');
  assert.match(fs.readFileSync(output, 'utf8'), /<svg[\s>]/);
  const graphBytes = fs.readFileSync(graph);
  const outputBytes = fs.readFileSync(output);

  // Simulate a matching prior release: existing component update must replace it safely.
  const receiptPath = path.join(workspace, 'components/buildr/archify/component.yml');
  const priorProgram = path.join(installed, 'assets/archify/bin/archify.mjs');
  fs.appendFileSync(priorProgram, '\n// prior-release fixture\n');
  const priorDefinition = YAML.parse(fs.readFileSync(receiptPath, 'utf8'));
  priorDefinition.version = '2.15.0+buildr.1';
  priorDefinition.integrity = [`skills/buildr/archify=${assetIntegrity(installed)}`];
  fs.writeFileSync(receiptPath, YAML.stringify(priorDefinition));
  run(['sync', 'codex', ...target]);
  assert.equal(assetIntegrity(installed), assetIntegrity(source));

  fs.appendFileSync(priorProgram, '\n// user modification\n');
  const modified = fs.readFileSync(priorProgram);
  run(['component', 'uninstall', 'archify', '--agent', 'codex', ...target], 1);
  assert.deepEqual(fs.readFileSync(priorProgram), modified);
  fs.copyFileSync(path.join(source, 'assets/archify/bin/archify.mjs'), priorProgram);
  run(['component', 'uninstall', 'archify', '--agent', 'codex', ...target]);
  assert.equal(fs.existsSync(installed), false);
  assert.equal(fs.existsSync(projected), false);
  assert.deepEqual(fs.readFileSync(graph), graphBytes);
  assert.deepEqual(fs.readFileSync(output), outputBytes);
  assert.equal(fs.readFileSync(path.join(external, 'SKILL.md'), 'utf8'), externalBody);
  run(['sync', 'codex', ...target]);
  assert.equal(fs.existsSync(installed), false, 'Explicit uninstall must survive sync.');
  process.stdout.write('Archify optional component lifecycle and installed rendering passed.\n');
}

if (process.argv.includes('--archify-scenario')) {
  scenario();
} else {
  test('Archify optional component installs, renders, updates and uninstalls without losing user content', { timeout: 180_000 }, () => {
    const result = spawnSync(process.execPath, [path.join(serviceRoot, 'tools/development/run-isolated-workspace-smoke.ts'),
      '--script', file, '--', '--archify-scenario'], {
      cwd: serviceRoot, encoding: 'utf8', timeout: 175_000, maxBuffer: 8 * 1024 * 1024,
    });
    assert.equal(result.status, 0, `${result.error?.message ?? ''}\n${result.stdout}\n${result.stderr}`);
    assert.match(result.stdout, /"cleanup":"cleaned"/);
  });
}
