import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { REQUIRED_RENDER_CAPABILITIES, createRuntimePlan } from '../../src/modules/agent-assets/infrastructure/runtime/adapter-contract.ts';
import { reconcileRuntimePlan } from '../../src/modules/agent-assets/infrastructure/runtime/runtime-reconciler.ts';
import {
  buildRetiredRuntimeProjectionPlan,
  listRetiredRuleBridgeTargets,
  retiredRuntimeProjectionFindings,
  retiredRuntimeProjectionInventory,
} from '../../src/modules/agent-assets/infrastructure/runtime/retired-adapters.ts';
import {
  buildSkillProjectionReceipt,
  renderSkillProjectionReceipt,
  sha256Integrity,
} from '../../src/modules/agent-assets/infrastructure/runtime/skills/projection-files.ts';

const RULE_MARKER = (adapterId: string, type = ''): string => `<!-- Generated by Buildr. Agent adapter: ${adapterId};${type} source: AGENTS.md; scope: .. Do not edit. -->`;
const ROOT_INDEX_GUIDANCE = [
  '执行任何 workspace 任务前，必须先读取并遵循根 `AGENTS.md`。',
  '每当读取、分析或修改某个文件或目录时，必须再读取从 workspace root 到该路径之间所有存在的 `AGENTS.md`，按由宽到窄的顺序应用；不得读取不相关兄弟目录的规则。',
  '下列索引仅用于发现规则文件，普通 Markdown 链接不代表内容已经自动加载：',
];

function fixture(t: any): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-retired-adapters-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  fs.mkdirSync(path.join(root, '.buildr', 'agent-runtime'), { recursive: true });
  fs.writeFileSync(path.join(root, 'AGENTS.md'), '# Workspace rules\n');
  return root;
}

function write(root: string, relative: string, content: string): string {
  const file = path.join(root, ...relative.split('/'));
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
  return file;
}

function skillEntries(root: string, relative: string): any[] {
  const directory = path.join(root, ...relative.split('/'));
  return fs.readdirSync(directory, { recursive: true, withFileTypes: true })
    .filter((entry: any) => entry.isFile())
    .map((entry: any) => {
      const file = path.join(entry.parentPath ?? entry.path, entry.name);
      return {
        path: path.relative(directory, file).split(path.sep).join('/'),
        integrity: sha256Integrity(fs.readFileSync(file)),
        executable: (fs.statSync(file).mode & 0o100) === 0o100,
      };
    });
}

function writeReceipt(root: string, owner: string, runtimePath: string, entries: any[], legacy = false): string {
  const directory = legacy
    ? path.join(root, '.qoder', 'buildr', 'skill-projection-receipts', owner)
    : path.join(root, '.buildr', 'agent-runtime', 'workspace', owner, 'skill-projection-ownership-receipts');
  fs.mkdirSync(directory, { recursive: true });
  const receipt = buildSkillProjectionReceipt({
    adapterId: owner,
    destination: 'workspace',
    skillId: runtimePath,
    runtimePath,
    sources: [`.skills/${runtimePath}`],
    assetIdentity: `buildr:skill:${runtimePath}`,
    sourceIdentity: `package:skills/buildr/${runtimePath}`,
    sourceWorkspaceId: 'retired-adapter-fixture',
    sourceDigest: sha256Integrity(Buffer.from(runtimePath, 'utf8')),
    files: entries,
  });
  const file = path.join(directory, `${runtimePath}.json`);
  fs.writeFileSync(file, renderSkillProjectionReceipt(receipt));
  return file;
}

function writeSkill(root: string, skillsRoot: string, skillId: string, companions: string[] = []): string {
  const directory = path.join(root, skillsRoot, 'skills', skillId);
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'SKILL.md'), `---\nname: ${skillId}\ndescription: ${skillId} fixture\n---\n\n# ${skillId}\n`);
  for (const companion of companions) {
    const file = path.join(directory, ...companion.split('/'));
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, `# ${companion}\n`);
  }
  return directory;
}

function writeRootIndexBridge(root: string, relative: string, adapterId: string, extra: string[] = []): string {
  return write(root, relative, [
    `<!-- Generated by Buildr. Agent adapter: ${adapterId}; type: root-index-reference. Do not edit. -->`,
    '',
    '# Buildr Rules Bridge',
    '',
    ...ROOT_INDEX_GUIDANCE,
    '',
    '- [AGENTS.md](AGENTS.md)',
    '',
    ...extra,
  ].join('\n'));
}

/** 完整投放：可证明归属的桥与镜像、无法证明的镜像、共享技能根、无法分离的 root-index 桥。 */
function seedRetiredProjections(root: string): void {
  write(root, '.qoder/rules/buildr/000-root-aaa.md', `---\ntrigger: always_on\n---\n${RULE_MARKER('qoder')}\n\n# AGENTS.md\n`);
  write(root, '.qoder/rules/buildr/002-scope-bbb.md', `---\ntrigger: always_on\n---\n${RULE_MARKER('qoder')}\n\n# Scope rules\n`);
  write(root, '.cursor/rules/buildr.mdc', `---\nalwaysApply: true\n---\n${RULE_MARKER('cursor')}\n\n# AGENTS.md\n`);
  write(root, '.trae/rules/buildr.md', `${RULE_MARKER('trae')}\n\n# AGENTS.md\n`);
  writeRootIndexBridge(root, 'CLAUDE.local.md', 'trae-work');

  writeSkill(root, '.qoder', 'alpha', ['references/guide.md']);
  writeReceipt(root, 'qoder', 'alpha', skillEntries(root, '.qoder/skills/alpha'));
  writeSkill(root, '.trae', 'delta');
  writeReceipt(root, 'trae-work', 'delta', skillEntries(root, '.trae/skills/delta'));
  writeSkill(root, '.codebuddy', 'omega');
  writeReceipt(root, 'workbuddy', 'omega', skillEntries(root, '.codebuddy/skills/omega'));
  writeSkill(root, '.qoder', 'legacy-skill');
  writeReceipt(root, 'qoder', 'legacy-skill', skillEntries(root, '.qoder/skills/legacy-skill'), true);

  // 无回执：无法证明所有权。
  writeSkill(root, '.qoder', 'beta');
  // 回执后内容被修改。
  writeSkill(root, '.qoder', 'gamma');
  writeReceipt(root, 'qoder', 'gamma', skillEntries(root, '.qoder/skills/gamma'));
  write(root, '.qoder/skills/gamma/SKILL.md', '---\nname: gamma\ndescription: gamma fixture\n---\n\n# gamma edited by user\n');
  // 回执未登记的额外条目。
  writeSkill(root, '.qoder', 'epsilon');
  writeReceipt(root, 'qoder', 'epsilon', skillEntries(root, '.qoder/skills/epsilon'));
  write(root, '.qoder/skills/epsilon/notes.md', '# user notes\n');

  // 共享技能根：由标准适配器拥有，退役清理不得触碰。
  writeSkill(root, '.agents', 'shared');
  writeReceipt(root, 'cursor', 'shared', skillEntries(root, '.agents/skills/shared'));

  // 无法安全分离：root-index 桥之外还有用户内容。
  writeRootIndexBridge(root, 'CODEBUDDY.md', 'workbuddy', ['## 我的本地说明', '', '这段内容属于用户。']);
}

function applyPlan(root: string, removals: any[], findings: any[] = []): any {
  const plan = createRuntimePlan({
    adapterId: 'agents-standard',
    runtimeId: 'agents-standard',
    targetRoot: root,
    scope: '.',
    capabilityEvidence: REQUIRED_RENDER_CAPABILITIES.map((capability: any) => ({ capability, supported: true })),
    removals,
    findings,
  });
  return reconcileRuntimePlan(plan);
}

function inventory(root: string): string[] {
  const files: string[] = [];
  const walk = (directory: string) => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const file = path.join(directory, entry.name);
      if (entry.isDirectory()) walk(file);
      else files.push(path.relative(root, file).split(path.sep).join('/'));
    }
  };
  walk(root);
  return files.sort();
}

function relativePaths(root: string, removals: any[]): string[] {
  return removals.map((item: any) => path.relative(root, item.targetFile).split(path.sep).join('/')).sort();
}

test('退役适配器的可证明投射被清理，缺回执或被修改的投射保留并报告', (t) => {
  const root = fixture(t);
  seedRetiredProjections(root);
  const retirement = buildRetiredRuntimeProjectionPlan({ targetRoot: root, adapterId: 'agents-standard', scope: '.' });
  const removed = relativePaths(root, retirement.removals);

  for (const target of [
    '.qoder/rules/buildr/000-root-aaa.md',
    '.qoder/rules/buildr/002-scope-bbb.md',
    '.qoder/skills/alpha/SKILL.md',
    '.qoder/skills/alpha/references/guide.md',
    '.buildr/agent-runtime/workspace/qoder/skill-projection-ownership-receipts/alpha.json',
    '.qoder/buildr/skill-projection-receipts/qoder/legacy-skill.json',
    '.cursor/rules/buildr.mdc',
    '.trae/rules/buildr.md',
    '.trae/skills/delta/SKILL.md',
    '.codebuddy/skills/omega/SKILL.md',
    'CLAUDE.local.md',
  ]) assert.ok(removed.includes(target), `expected retirement removal: ${target}`);

  for (const retained of ['.qoder/skills/beta/SKILL.md', '.qoder/skills/gamma/SKILL.md', '.qoder/skills/epsilon/SKILL.md', '.agents/skills/shared/SKILL.md', 'CODEBUDDY.md']) {
    assert.ok(!removed.includes(retained), `must not retire unprovable or user-owned path: ${retained}`);
  }

  const retained = retirement.retained.map((finding: any) => finding.path).join('\n');
  assert.match(retained, /\.qoder\/skills\/beta/, 'missing receipt must be reported');
  assert.match(retained, /\.qoder\/skills\/gamma/, 'modified mirror must be reported');
  assert.match(retained, /\.qoder\/skills\/epsilon/, 'unregistered extra entry must be reported');
  assert.ok(retirement.retained.every((finding: any) => finding.userActionRequired === false), 'retained findings must not block other work');

  const result = applyPlan(root, retirement.removals, []);
  assert.ok(result.removed.length > 0);
  for (const target of ['.qoder/rules/buildr', '.qoder/skills/alpha', '.cursor', '.trae/rules', '.trae/skills/delta', '.codebuddy/skills/omega']) {
    assert.equal(fs.existsSync(path.join(root, target)), false, `${target} must be gone after teardown`);
  }
  assert.equal(fs.existsSync(path.join(root, '.buildr/agent-runtime/workspace/qoder/skill-projection-ownership-receipts/alpha.json')), false, 'retired Skill receipt must be removed');
  assert.equal(fs.existsSync(path.join(root, '.buildr/agent-runtime/workspace/trae-work')), false, 'retired state namespace must be pruned once empty');
  assert.equal(fs.existsSync(path.join(root, '.buildr/agent-runtime/workspace/workbuddy')), false, 'retired state namespace must be pruned once empty');
  assert.equal(fs.existsSync(path.join(root, '.buildr/agent-runtime/workspace/qoder/skill-projection-ownership-receipts/gamma.json')), true, 'receipts that cannot prove ownership must stay with their namespace');
  assert.equal(fs.readFileSync(path.join(root, '.agents/skills/shared/SKILL.md'), 'utf8').includes('shared'), true, 'shared standard Skill root must stay');
  assert.equal(fs.existsSync(path.join(root, '.qoder/skills/beta/SKILL.md')), true, 'unprovable mirror must stay');
  assert.equal(fs.existsSync(path.join(root, 'CODEBUDDY.md')), true, 'user-owned root index must stay');
});

test('受管桥与用户内容无法分离时整组零写入并报告冲突', (t) => {
  const root = fixture(t);
  seedRetiredProjections(root);
  const retirement = buildRetiredRuntimeProjectionPlan({ targetRoot: root, adapterId: 'agents-standard', scope: '.' });
  const conflicts = retirement.findings.filter((finding: any) => finding.status === 'conflict');
  assert.deepEqual(conflicts.map((finding: any) => finding.path), ['CODEBUDDY.md']);
  const before = inventory(root);
  assert.throws(() => applyPlan(root, retirement.removals, retirement.findings), /no files were changed/);
  assert.deepEqual(inventory(root), before, 'a retirement conflict must not change any file');
});

test('退役清理重复执行幂等，非标准适配器与局部 scope 不触碰退役投射', (t) => {
  const root = fixture(t);
  seedRetiredProjections(root);
  const first = buildRetiredRuntimeProjectionPlan({ targetRoot: root, adapterId: 'agents-standard', scope: '.' });
  applyPlan(root, first.removals, []);
  const after = inventory(root);

  const second = buildRetiredRuntimeProjectionPlan({ targetRoot: root, adapterId: 'agents-standard', scope: '.' });
  const secondPaths = relativePaths(root, second.removals);
  for (const target of ['.qoder/skills/alpha/SKILL.md', '.buildr/agent-runtime/workspace/qoder/skill-projection-ownership-receipts/alpha.json', 'CLAUDE.local.md']) {
    assert.ok(!secondPaths.includes(target), `idempotent run must not plan an already retired path: ${target}`);
  }
  const result = applyPlan(root, second.removals, []);
  assert.deepEqual(result.changed, []);
  assert.deepEqual(result.removed, []);
  assert.deepEqual(inventory(root), after, 'a repeated run must not change the workspace');

  for (const options of [{ adapterId: 'claude-code' }, { adapterId: 'agents-standard', scope: 'projects/product' }]) {
    const plan = buildRetiredRuntimeProjectionPlan({ targetRoot: root, ...options });
    assert.deepEqual(plan.removals, []);
    assert.deepEqual(plan.findings, []);
  }
  const doctorFindings = retiredRuntimeProjectionFindings(root);
  assert.deepEqual(
    doctorFindings.filter((finding: any) => finding.status === 'conflict').map((finding: any) => finding.path),
    ['CODEBUDDY.md'],
    'doctor keeps reporting the projection that cannot be separated',
  );
  assert.ok(doctorFindings.some((finding: any) => finding.code === 'runtime.retired_projection_retained'), 'doctor reports retained retired projections with their reason');
  assert.ok(doctorFindings.every((finding: any) => finding.userActionRequired === (finding.status === 'conflict')));
});

test('退役投射清单声明五个适配器的桥与技能根，并忽略非退役标记', (t) => {
  const root = fixture(t);
  write(root, '.qoder/rules/buildr/user-note.md', '# 用户自己的规则\n');
  write(root, '.cursor/rules/buildr.mdc', `${RULE_MARKER('claude-code')}\n\n# AGENTS.md\n`);
  write(root, 'CODEBUDDY.md', '# 用户自己的说明\n');
  const inventoryReport = retiredRuntimeProjectionInventory(root);
  assert.equal(inventoryReport.schemaVersion, 'buildr.retired-runtime-projection-inventory/v1');
  assert.deepEqual(inventoryReport.adapters.map((adapter: any) => adapter.id), ['cursor', 'qoder', 'trae', 'trae-work', 'workbuddy']);
  assert.deepEqual(
    inventoryReport.adapters.filter((adapter: any) => adapter.sharedSkillsRoot).map((adapter: any) => adapter.id),
    ['cursor', 'trae'],
    'shared .agents Skill root stays with the standard adapter',
  );
  assert.deepEqual(listRetiredRuleBridgeTargets(root), []);
  const plan = buildRetiredRuntimeProjectionPlan({ targetRoot: root, adapterId: 'agents-standard', scope: '.' });
  assert.deepEqual(plan.removals, [], 'a bridge owned by another adapter or by the user must not be retired');
  assert.deepEqual(plan.findings, []);
});
