import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { consumeRuntimeAdapterOption, detectManagedRuntimeAdapters, parseRuntimeCommandArgs, selectWorkspaceRuntime } from '../../src/modules/agent-assets/application/runtime-selection.ts';
import { createAgentAssetsCliContributions } from '../../src/modules/agent-assets/interfaces/cli/agent-assets.ts';
import { withResolvedTarget } from '../../src/infrastructure/cli-arguments.ts';

function workspace(t: any) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'buildr-runtime-selection-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  return root;
}
function receipt(root: string, adapterId: string) {
  const file = path.join(root, '.buildr', 'agent-runtime', 'workspace', adapterId, 'skill-projection-ownership-receipts', 'demo.json');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  // Discovery observes ownership evidence without swallowing a future receipt-validation error.
  fs.writeFileSync(file, 'invalid receipt retained for the operation to diagnose');
  return file;
}

test('运行时省略保留全部选项，显式适配器与真实身份独立解析', () => {
  assert.deepEqual(parseRuntimeCommandArgs(['--target', '/workspace', '--adapter', 'cursor']), { runtimeId: null, args: ['--target', '/workspace', '--adapter', 'cursor'] });
  assert.deepEqual(parseRuntimeCommandArgs(['dsh', '--target', '/workspace']), { runtimeId: 'dsh', args: ['--target', '/workspace'] });
  assert.deepEqual(consumeRuntimeAdapterOption(['--target', '/workspace', '--adapter', 'cursor']), { adapterId: 'cursor', args: ['--target', '/workspace'] });
  assert.throws(() => consumeRuntimeAdapterOption(['--adapter']), /Missing value/);
  assert.throws(() => consumeRuntimeAdapterOption(['--adapter', 'cursor', '--adapter', 'qoder']), /Duplicate option/);
});

test('空现场默认标准，已有回执保留方式但不推断宿主品牌', (t) => {
  const root = workspace(t);
  assert.equal(selectWorkspaceRuntime(root).adapterId, 'agents-standard');
  assert.equal(selectWorkspaceRuntime(root).runtimeId, null);
  receipt(root, 'claude-code');
  const selected = selectWorkspaceRuntime(root);
  assert.equal(selected.adapterId, 'claude-code');
  assert.equal(selected.runtimeId, null);
  assert.equal(selected.reason, 'workspace-detected');
  assert.equal(selectWorkspaceRuntime(root, { runtimeId: 'dsh' }).adapterId, 'agents-standard');
  assert.equal(selectWorkspaceRuntime(root, { runtimeId: 'new-host', adapterId: 'cursor' }).runtimeId, 'new-host');
  assert.throws(() => selectWorkspaceRuntime(root, { adapterId: 'typo' }), /Unsupported runtime adapter/);
});

test('旧Codex回执属于标准方式，多例外写入要求选择，只读盘点保留全部', (t) => {
  const root = workspace(t);
  receipt(root, 'codex');
  assert.deepEqual(detectManagedRuntimeAdapters(root), ['agents-standard']);
  receipt(root, 'claude-code');
  assert.deepEqual(detectManagedRuntimeAdapters(root), ['claude-code', 'agents-standard']);
  assert.throws(() => selectWorkspaceRuntime(root), /Multiple managed runtime adapters/);
  assert.equal(selectWorkspaceRuntime(root, { adapterId: 'claude-code' }).runtimeId, null);
});

test('共享标准回执不会让唯一专用规则接入产生额外歧义', (t) => {
  const root = workspace(t);
  receipt(root, 'agents-standard');
  const rule = path.join(root, '.cursor', 'rules', 'buildr.mdc');
  fs.mkdirSync(path.dirname(rule), { recursive: true });
  fs.writeFileSync(rule, '<!-- Generated by Buildr. Agent adapter: cursor; type: test. -->\n');
  assert.equal(selectWorkspaceRuntime(root).adapterId, 'cursor');
  assert.equal(selectWorkspaceRuntime(root).runtimeId, null);
});

test('只读规则证据识别root-index方式且不穿越嵌套Workspace', (t) => {
  const root = workspace(t);
  fs.writeFileSync(path.join(root, 'CODEBUDDY.md'), '<!-- Generated by Buildr. Agent adapter: workbuddy; type: root-index-reference. -->\n');
  const nested = path.join(root, 'nested');
  fs.mkdirSync(path.join(nested, '.buildr'), { recursive: true });
  fs.writeFileSync(path.join(nested, '.buildr', 'workspace.yml'), 'schemaVersion: buildr.workspace/v1\n');
  fs.writeFileSync(path.join(nested, 'CLAUDE.local.md'), '<!-- Generated by Buildr. Agent adapter: trae-work; type: root-index-reference. -->\n');
  assert.deepEqual(detectManagedRuntimeAdapters(root), ['workbuddy']);
});

test('现场读取错误不能变成标准默认值', (t) => {
  const root = workspace(t);
  receipt(root, 'claude-code');
  t.mock.method(fs, 'readdirSync', () => { throw Object.assign(new Error('injected evidence read failure'), { code: 'EACCES' }); });
  assert.throws(() => selectWorkspaceRuntime(root), /injected evidence read failure/);
});

test('命令路由不吞省略运行时后的target，运行失败不尝试其他实现', (t) => {
  t.mock.method(console, 'log', () => {});
  const calls: any[] = [];
  const runtime = {
    withResolvedTarget,
    renderRuntime: (identity: any, args: any) => { calls.push(['render', identity, args]); return { targetRoot: '/workspace', files: [], rulesActions: [], warnings: [] }; },
    syncRuntime: (identity: any, args: any) => { calls.push(['sync', identity, args]); throw new Error('selected runtime failed'); },
    renderSkillsRuntime: (identity: any, args: any) => { calls.push(['skills', identity, args]); return { targetRoot: '/workspace', files: [], jsonReported: true }; },
    renderRulesRuntime: (identity: any, args: any) => { calls.push(['rules', identity, args]); return { targetRoot: '/workspace', files: [], actions: [] }; },
    installProductRuntimeSkill: (identity: any, args: any) => { calls.push(['install', identity, args]); return { targetRoot: '/workspace', files: [] }; },
  };
  const routes = createAgentAssetsCliContributions();
  for (const key of ['render', 'skills render', 'rules render', 'skill install']) {
    const argv = ['node', 'buildr', ...key.split(' '), '--target', '/workspace', '--adapter', 'agents-standard'];
    routes.find((item: any) => item.key === key).run(runtime, { argv, domain: key.split(' ')[0] });
    assert.equal(calls.at(-1)[1], null);
    assert.deepEqual(calls.at(-1)[2], ['--target', '/workspace', '--adapter', 'agents-standard']);
  }
  const before = calls.length;
  assert.throws(() => routes.find((item: any) => item.key === 'sync').run(runtime, { argv: ['node', 'buildr', 'sync', '--target', '/workspace'] }), /selected runtime failed/);
  assert.equal(calls.length, before + 1);
});

test('未登记的嵌套代码库不影响外层选择，旧受管Skill标记仍可发现', (t) => {
  const root = workspace(t);
  const foreign = path.join(root, 'foreign');
  fs.mkdirSync(path.join(foreign, '.git'), { recursive: true });
  fs.writeFileSync(path.join(foreign, 'CLAUDE.md'), '<!-- Generated by Buildr. -->\n@AGENTS.md\n');
  assert.deepEqual(detectManagedRuntimeAdapters(root), []);
  const skill = path.join(root, '.claude', 'skills', 'buildr', 'SKILL.md');
  fs.mkdirSync(path.dirname(skill), { recursive: true });
  fs.writeFileSync(skill, '<!-- Generated by Buildr. Hash: legacy. Do not edit. -->\n# Buildr\n');
  assert.equal(selectWorkspaceRuntime(root).adapterId, 'claude-code');
});

test('回执祖先符号链接不会被跟随或解释成缺省标准', { skip: process.platform === 'win32' }, (t) => {
  const root = workspace(t);
  const external = workspace(t);
  fs.symlinkSync(external, path.join(root, '.buildr'));
  assert.throws(() => selectWorkspaceRuntime(root), /symbolic link/);
});
