import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';
import test, { after } from 'node:test';
import { createRuntime } from '../helpers/runtime-harness.ts';
import { createLocalWorkspaceServer } from '../../src/web/http/server.ts';
import { cleanupLocalTaskLifecycleSystemContext } from '../helpers/task-lifecycle-system-context.ts';
import { taskRecordFixture } from '../helpers/task-record-system-fixture.ts';
import { WORKBENCH_HTTP_SCHEMAS, WORKBENCH_HTTP_VALIDATORS } from '../../src/modules/workbench/interfaces/http/workbench-http-schema.ts';
import { checkWorkbenchDto } from '../../tools/codegen/contracts/workbench-dto.ts';

after(() => cleanupLocalTaskLifecycleSystemContext());
function schema(name: string, input: unknown) { const result = WORKBENCH_HTTP_VALIDATORS.validate(WORKBENCH_HTTP_SCHEMAS[name].$id, input); assert.equal(result.valid, true, JSON.stringify(result.errors)); }

test('工作台HTTP真实读写共享CLI事实并保护会话、输入、事项身份与观察版本', async (t) => {
  const { base, root } = taskRecordFixture(t, 'workbench-http');
  const previous = process.env.BUILDR_APP_DATA_DIR;
  process.env.BUILDR_APP_DATA_DIR = path.join(base, 'http-app-data');
  t.after(() => { if (previous === undefined) delete process.env.BUILDR_APP_DATA_DIR; else process.env.BUILDR_APP_DATA_DIR = previous; });
  const runtime = createRuntime();
  const original = runtime.createTask(root, { taskId: 'http-task', title: '接口验证', intent: '验证工作台的真实协作', status: 'todo', projects: ['demo'], services: [], changes: [] });
  runtime.createTask(root, { taskId: 'work-contexts', title: '与批量入口同名的旧任务', intent: '旧任务路径保持可读', status: 'todo', projects: [], services: [], changes: [] });
  const instance = createLocalWorkspaceServer(runtime, { targetRoot: root });
  t.after(() => new Promise<void>((resolve) => instance.server.close(() => resolve())));
  const { url, initialWorkspaceId, sessionToken } = await instance.ready;
  const prefix = `${url}/api/v1/workspaces/${initialWorkspaceId}`;
  const headers = { origin: url, 'x-buildr-session': sessionToken, 'content-type': 'application/json' };
  const get = async (suffix: string) => { const response = await fetch(prefix + suffix); return { status: response.status, body: await response.json() }; };
  const write = async (suffix: string, method: string, body?: unknown, selectedHeaders: Record<string, string> = headers) => {
    const response = await fetch(prefix + suffix, { method, headers: selectedHeaders, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { status: response.status, body: await response.json() };
  };
  const databaseFile = path.join(root, '.buildr/local/workspace.sqlite');
  const beforeRead = fs.readFileSync(databaseFile);
  for (const endpoint of ['/workbench', '/workbench/preferences', '/tasks/http-task/work-context', '/tasks/work-contexts?ids=http-task']) assert.equal((await get(endpoint)).status, 200);
  assert.deepEqual(fs.readFileSync(databaseFile), beforeRead, '纯读取不得改变工作空间数据库');
  assert.equal((await get('/tasks/work-contexts')).body.record.taskId, 'work-contexts');
  let read = await get('/tasks/http-task/work-context');
  assert.equal(read.status, 200); schema('TaskWorkContextResponse', read.body); assert.equal(read.body.context, null);
  let result = await write('/tasks/http-task/work-context', 'PUT', { expectedContextDigest: 'absent', progress: '已形成方案', nextStep: '等待确认', attention: { kind: 'decision', reason: '确认范围' } }, { 'content-type': 'application/json' });
  assert.equal(result.status, 403);
  assert.equal(runtime.inspectTaskWorkContext(root, 'http-task').context, null);
  result = await write('/tasks/http-task/work-context', 'PUT', { expectedContextDigest: 'absent', progress: '已形成方案', nextStep: '等待确认', forbidden: true });
  assert.equal(result.status, 400); schema('WorkbenchErrorResponse', result.body);
  result = await write('/tasks/http-task/work-context', 'PUT', { expectedContextDigest: 'absent', progress: '已形成方案', nextStep: '等待确认', attention: { kind: 'decision', reason: '确认范围' } });
  assert.equal(result.status, 200); schema('TaskWorkContextResponse', result.body);
  const created = result.body;
  read = await get('/tasks/work-contexts?ids=http-task');
  assert.equal(read.status, 200); schema('TaskWorkContextsResponse', read.body); assert.deepEqual(read.body.items[0], created);
  assert.equal((await get('/tasks/work-contexts?ids=http-task&ids=http-task')).status, 400);
  result = await write('/tasks/http-task/work-context/respond', 'POST', { expectedContextDigest: created.contextDigest, attentionId: 'stale-id', response: '继续' });
  assert.equal(result.status, 409);
  result = await write('/tasks/http-task/work-context/respond', 'POST', { expectedContextDigest: created.contextDigest, attentionId: created.context.attention.id, response: '先实现阅读' });
  assert.equal(result.status, 200); schema('TaskWorkContextResponse', result.body);
  assert.equal(runtime.inspectTaskWorkContext(root, 'http-task').context.attention.response.text, '先实现阅读');
  assert.equal((await write('/tasks/http-task/work-context/respond', 'POST', { expectedContextDigest: created.contextDigest, attentionId: created.context.attention.id, response: '旧版响应' })).status, 409);
  result = await write('/workbench/preferences/planned-task/http-task', 'PUT', {});
  assert.equal(result.status, 200); schema('WorkbenchPreferencesResponse', result.body);
  const beforeDeniedDelete = result.body;
  const deniedDelete = await write('/workbench/preferences/planned-task/http-task', 'DELETE', undefined, {});
  assert.equal(deniedDelete.status, 403);
  assert.deepEqual((await get('/workbench/preferences')).body, beforeDeniedDelete);
  result = await write('/workbench/preferences/planned-task/http-task', 'DELETE');
  assert.equal(result.status, 200); assert.equal(result.body.items.length, 0);
  result = await write('/workbench/visits', 'POST', { key: 'task:http-task', label: '接口验证', href: `/workspaces/${initialWorkspaceId}/tasks/http-task` });
  assert.equal(result.status, 200);
  result = await write('/workbench/preferences/saved-resource/evil', 'PUT', { label: '外部', href: 'https://example.com' });
  assert.equal(result.status, 400);
  read = await get('/workbench'); assert.equal(read.status, 200); schema('WorkbenchResponse', read.body);
  assert.equal(read.body.attention.total, 0);
  assert.equal(runtime.inspectTask(root, 'http-task').recordDigest, original.recordDigest);
  assert.equal((await get('/workbench?root=/etc')).status, 400);
  assert.equal((await get('/workbench?date=2026-02-30')).status, 400);
  assert.equal((await get('/workbench?project=demo&project=other')).status, 400);
  assert.deepEqual(await checkWorkbenchDto(), []);
});
