import fs from 'node:fs';
import path from 'node:path';
import { hasManagedSkillMarker } from '../infrastructure/runtime/render-claude-code.ts';
import { RUNTIME_ADAPTERS, resolveRuntimeSelection } from '../infrastructure/runtime/adapter-contract.ts';
import { buildRuleDiscoveryPlan, hasManagedRulesMarker, resolveRuleScope } from '../infrastructure/runtime/render-claude-code-rules.ts';

export type RuntimeSelectionInput = { runtimeId?: string | null; adapterId?: string | null };
export type RuntimeSelection = ReturnType<typeof resolveRuntimeSelection>;
const EXCLUDED = new Set(['.git', '.hg', '.svn', '.buildr', '.worktrees', '.agents', '.claude', '.codex', '.cursor', '.qoder', '.trae', '.codebuddy', '.workbuddy', 'node_modules', 'vendor', 'dist', 'build', 'coverage']);

function statIfPresent(file: string) {
  try { return fs.lstatSync(file); } catch (error: any) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

function containsReceipt(directory: string): boolean {
  const stat = statIfPresent(directory);
  if (!stat) return false;
  if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`Runtime ownership evidence must be a directory, not a symbolic link: ${directory}`);
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) throw new Error(`Runtime ownership evidence must not traverse a symbolic link: ${path.join(directory, entry.name)}`);
    if (entry.isFile() && entry.name.endsWith('.json')) return true;
    if (entry.isDirectory() && containsReceipt(path.join(directory, entry.name))) return true;
  }
  return false;
}

function containsManagedSkill(directory: string): boolean {
  const stat = statIfPresent(directory);
  if (!stat) return false;
  if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error(`Runtime Skill evidence must be a directory, not a symbolic link: ${directory}`);
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Runtime Skill evidence must not traverse a symbolic link: ${file}`);
    if (entry.isDirectory() && containsManagedSkill(file)) return true;
    if (entry.isFile() && entry.name === 'SKILL.md' && hasManagedSkillMarker(fs.readFileSync(file, 'utf8'))) return true;
  }
  return false;
}

function managedRules(file: string, adapterId: string): boolean {
  const stat = statIfPresent(file);
  if (!stat) return false;
  if (stat.isSymbolicLink()) throw new Error(`Runtime rules evidence must not be a symbolic link: ${file}`);
  if (!stat.isFile()) return false;
  const content = fs.readFileSync(file, 'utf8');
  return adapterId === 'claude-code'
    ? hasManagedRulesMarker(content)
    : content.includes(`<!-- Generated by Buildr. Agent adapter: ${adapterId};`);
}

function assertEvidencePath(root: string, file: string): void {
  let current = root;
  for (const part of path.relative(root, file).split(path.sep)) {
    current = path.join(current, part);
    const stat = statIfPresent(current);
    if (!stat) return;
    if (stat.isSymbolicLink()) throw new Error(`Runtime evidence must not traverse a symbolic link: ${current}`);
  }
}

/** Observe ownership only: do not assemble a projection or turn an operation failure into absence. */
export function detectManagedRuntimeAdapters(targetRoot: string): string[] {
  const root = path.resolve(targetRoot);
  const rootStat = statIfPresent(root);
  if (!rootStat) return [];
  if (!rootStat.isDirectory()) throw new Error(`Target directory does not exist: ${root}`);
  const present = new Set<string>();
  const descriptors = Object.values(RUNTIME_ADAPTERS) as any[];
  for (const adapter of descriptors) {
    if (adapter.id === 'agents-standard' || adapter.traits.skills.root !== '.agents') {
      const skills = path.join(root, adapter.traits.skills.root, 'skills');
      assertEvidencePath(root, skills);
      if (containsManagedSkill(skills)) present.add(adapter.id);
    }
    const ids = adapter.id === 'agents-standard' ? ['agents-standard', 'codex'] : [adapter.id];
    for (const id of ids) {
      const locations = [
        path.join(root, '.buildr', 'agent-runtime', 'workspace', id, 'skill-projection-ownership-receipts'),
        path.join(root, adapter.traits.skills.root, 'buildr', 'skill-projection-receipts', id),
        path.join(root, adapter.traits.skills.root, 'buildr', 'skill-satisfaction', id),
      ];
      for (const location of locations) {
        assertEvidencePath(root, location);
        if (containsReceipt(location)) present.add(adapter.id);
      }
    }
  }
  const discovery = buildRuleDiscoveryPlan(root, resolveRuleScope(root, '.'));
  const boundaries = new Set(discovery.boundaries.map((item: any) => path.resolve(root, item.path)));
  const rulesEvidence = (file: string, adapterId: string) => {
    assertEvidencePath(root, file);
    return managedRules(file, adapterId);
  };
  function visit(directory: string) {
    for (const adapter of descriptors) {
      const rules = adapter.traits.rules;
      if (rules.kind === 'native-recursive') continue;
      if (rules.targetPattern?.startsWith('<source-dir>/')) {
        const relative = rules.targetPattern.slice('<source-dir>/'.length);
        if (rulesEvidence(path.join(directory, relative), adapter.id)) present.add(adapter.id);
      } else if (directory === root && rules.placement === 'root-index') {
        if (rulesEvidence(path.join(root, rules.targetPattern.replace('<workspace-root>/', '')), adapter.id)) present.add(adapter.id);
      } else if (directory === root && adapter.id === 'qoder') {
        const qoderRoot = path.join(root, '.qoder', 'rules', 'buildr');
        const stat = statIfPresent(qoderRoot);
        if (stat?.isSymbolicLink()) throw new Error(`Runtime rules evidence must not be a symbolic link: ${qoderRoot}`);
        if (stat?.isDirectory()) for (const entry of fs.readdirSync(qoderRoot, { withFileTypes: true })) {
          if (entry.name.endsWith('.md') && rulesEvidence(path.join(qoderRoot, entry.name), adapter.id)) present.add(adapter.id);
        }
      }
    }
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      if (!entry.isDirectory() || entry.isSymbolicLink() || EXCLUDED.has(entry.name)) continue;
      const child = path.join(directory, entry.name);
      if (boundaries.has(path.resolve(child))) continue;
      // A nested Workspace owns its own runtime selection.
      if (statIfPresent(path.join(child, '.buildr', 'workspace.yml'))) continue;
      visit(child);
    }
  }
  visit(root);
  return descriptors.map(adapter => adapter.id).filter(id => present.has(id));
}

export function selectWorkspaceRuntime(targetRoot: string, input: RuntimeSelectionInput = {}): RuntimeSelection {
  if (input.runtimeId != null || input.adapterId != null) return resolveRuntimeSelection(input);
  const detected = detectManagedRuntimeAdapters(targetRoot);
  // A shared standard Skills receipt does not add a second choice beside its vendor rule adapter.
  const hasSharedVendor = detected.some(id => id !== 'agents-standard' && RUNTIME_ADAPTERS[id].traits.skills.root === '.agents');
  const choices = detected.filter(id => id !== 'agents-standard' || !hasSharedVendor);
  if (choices.length > 1) throw new Error(`Multiple managed runtime adapters are present: ${choices.join(', ')}. Select a runtime or use --adapter before writing.`);
  if (choices.length === 1) return { ...resolveRuntimeSelection({ adapterId: choices[0] }), reason: 'workspace-detected' };
  return resolveRuntimeSelection();
}

export function runtimeCommandSelector(selection: RuntimeSelection): string {
  return `${selection.runtimeId === null ? '' : ` ${selection.runtimeId}`} --adapter ${selection.adapterId}`;
}

/** Consume only the adapter option; the operation remains responsible for its own option validation. */
export function consumeRuntimeAdapterOption(args: string[]): { args: string[]; adapterId: string | null } {
  const remaining: string[] = [];
  let adapterId: string | null = null;
  for (let index = 0; index < args.length; index += 1) {
    if (args[index] !== '--adapter') { remaining.push(args[index]); continue; }
    if (adapterId !== null) throw new Error('Duplicate option: --adapter');
    const value = args[++index];
    if (!value || value.startsWith('--')) throw new Error('Missing value for --adapter');
    adapterId = value;
  }
  return { args: remaining, adapterId };
}

export function parseRuntimeCommandArgs(args: string[]): { runtimeId: string | null; args: string[] } {
  return args[0] && !args[0].startsWith('--')
    ? { runtimeId: args[0], args: args.slice(1) }
    : { runtimeId: null, args: [...args] };
}

export function validateRuntimeOperationArgs(args: string[], flags: readonly string[], booleans: readonly string[] = []): void {
  const allowed = new Set(flags);
  const booleanFlags = new Set(booleans);
  for (let index = 0; index < args.length; index += 1) {
    const flag = args[index];
    if (!allowed.has(flag)) throw new Error(`Unknown argument: ${flag}`);
    if (booleanFlags.has(flag)) continue;
    const value = args[++index];
    if (!value || value.startsWith('--')) throw new Error(`Missing value for ${flag}`);
  }
}
