import fs from 'node:fs';
import path from 'node:path';
import {
  parseSkillProjectionReceipt,
  runtimeFileMatches,
  sha256Integrity,
  SKILL_PROJECTION_OWNERSHIP_RECEIPTS_DIRECTORY,
} from './skills/projection-files.ts';
import { hasManagedRulesMarker } from './rule-projection.ts';

/**
 * 退役适配器的既有投射清理。
 *
 * `cursor`、`qoder`、`trae`、`trae-work`、`workbuddy` 不再是 supported adapter，
 * 但它们此前写过的规则桥、技能镜像与状态命名空间仍可能留在磁盘上。本模块只声明
 * 这些投射的位置与证明所有权的方法，不自己写文件：结果交给受管管线
 * （`assembleRuntimeProjection` 的 removals 与 `reconcileRuntimePlan`），
 * 从而复用写入前冲突预检、整组零写入、projection lock 与 changed 报告。
 *
 * 所有权规则：
 * - 规则桥：文件含 Buildr adapter 受管标记，且标记命名的 adapter 是退役 adapter。
 * - 技能镜像：`skill-projection-ownership-receipts` 回执能逐文件证明当前内容，
 *   且不含未知额外条目、受管文件未被修改。
 * - 无法证明所有权时只保留并报告，不猜测、不删除。
 * - 受管内容与用户内容无法安全分离时报告冲突，由受管管线整组零写入。
 */

export const RETIRED_ADAPTER_RULE_MARKER = '<!-- Generated by Buildr. Agent adapter:';
export const RETIRED_PROJECTION_RETAINED_CODE = 'runtime.retired_projection_retained';
export const RETIRED_PROJECTION_CONFLICT_CODE = 'runtime.retired_projection_conflict';

const RULE_MARKER_OWNER_PATTERN = /<!-- Generated by Buildr\. Agent adapter: ([A-Za-z0-9._-]+);/;
const ROOT_INDEX_MARKER_PATTERN = /^<!-- Generated by Buildr\. Agent adapter: ([A-Za-z0-9._-]+); type: root-index-reference\. Do not edit\. -->$/;
const ROOT_INDEX_BRIDGE_HEADING = '# Buildr Rules Bridge';
// 历史 root-index 桥的固定说明行：只有标题、这些行、空行与规则索引链接属于 Buildr。
const ROOT_INDEX_BRIDGE_GUIDANCE = Object.freeze([
  '执行任何 workspace 任务前，必须先读取并遵循根 `AGENTS.md`。',
  '每当读取、分析或修改某个文件或目录时，必须再读取从 workspace root 到该路径之间所有存在的 `AGENTS.md`，按由宽到窄的顺序应用；不得读取不相关兄弟目录的规则。',
  '下列索引仅用于发现规则文件，普通 Markdown 链接不代表内容已经自动加载：',
]);
const ROOT_INDEX_LINK_PATTERN = /^- \[[^\]]+\]\([^)]+\)$/;
const PROJECTION_NAMESPACE_SEGMENTS = Object.freeze(['.buildr', 'agent-runtime', 'workspace']);
// 与既有 vendor 规则发现保持一致：不进入 VCS 元数据、其他品牌根与构建产物。
const RETIRED_DISCOVERY_EXCLUDED = new Set([
  '.git', '.hg', '.svn', '.worktrees', '.agents', '.claude', '.cursor', '.qoder', '.trae',
  '.codebuddy', '.workbuddy', 'node_modules', 'vendor', 'dist', 'build', 'coverage',
]);

/**
 * 退役适配器的投射清单：规则桥位置与技能根。
 * `sharedSkillsRoot` 表示该技能根由标准适配器继续拥有；这类根下的技能文件与回执
 * 不属于退役对象，只由标准适配器自己的 orphan 与回执管线管辖
 * （对照 `projection-files.ts` 的 `SHARED_SKILL_OWNERS`）。
 */
export const RETIRED_RUNTIME_ADAPTERS: readonly any[] = Object.freeze([
  Object.freeze({
    id: 'cursor',
    displayName: 'Cursor',
    skills: Object.freeze({ root: '.agents', sharedSkillsRoot: true }),
    bridges: Object.freeze([Object.freeze({ kind: 'per-source', relative: path.join('.cursor', 'rules', 'buildr.mdc') })]),
  }),
  Object.freeze({
    id: 'qoder',
    displayName: 'Qoder',
    skills: Object.freeze({ root: '.qoder', sharedSkillsRoot: false }),
    bridges: Object.freeze([Object.freeze({ kind: 'workspace-directory', relative: path.join('.qoder', 'rules', 'buildr') })]),
  }),
  Object.freeze({
    id: 'trae',
    displayName: 'TRAE',
    skills: Object.freeze({ root: '.agents', sharedSkillsRoot: true }),
    bridges: Object.freeze([Object.freeze({ kind: 'per-source', relative: path.join('.trae', 'rules', 'buildr.md') })]),
  }),
  Object.freeze({
    id: 'trae-work',
    displayName: 'TRAE Work',
    skills: Object.freeze({ root: '.trae', sharedSkillsRoot: false }),
    bridges: Object.freeze([Object.freeze({ kind: 'root-index', relative: 'CLAUDE.local.md' })]),
  }),
  Object.freeze({
    id: 'workbuddy',
    displayName: 'WorkBuddy',
    skills: Object.freeze({ root: '.codebuddy', sharedSkillsRoot: false }),
    bridges: Object.freeze([Object.freeze({ kind: 'root-index', relative: 'CODEBUDDY.md' })]),
  }),
]);

export function retiredRuntimeAdapterIds(): string[] {
  return RETIRED_RUNTIME_ADAPTERS.map((adapter: any) => adapter.id);
}

export function isRetiredRuntimeAdapter(adapterId: any): boolean {
  return RETIRED_RUNTIME_ADAPTERS.some((adapter: any) => adapter.id === adapterId);
}

export function retiredRuntimeAdapter(adapterId: any): any {
  return RETIRED_RUNTIME_ADAPTERS.find((adapter: any) => adapter.id === adapterId) || null;
}

/** 与既有 `adapterRuleManaged` 等价的所有权证明：文件含 Buildr 受管标记。 */
export function retiredAdapterRuleManaged(content: any): boolean {
  return typeof content === 'string' && content.includes(RETIRED_ADAPTER_RULE_MARKER);
}

/** 读取受管标记声明的 adapter 身份；标记缺失时返回 null。 */
export function retiredAdapterRuleMarkerOwner(content: any): string | null {
  if (typeof content !== 'string') return null;
  return RULE_MARKER_OWNER_PATTERN.exec(content)?.[1] ?? null;
}

/**
 * 规则桥是否受 Buildr 管理。
 * root-index 桥的受管标记就是首行，直接复用共享的 `hasManagedRulesMarker`；
 * 目录型桥的标记位于 YAML frontmatter 之后，共享判断只看首行、覆盖不到，
 * 因此用 adapter 标记判断受管状态，再用 `retiredAdapterRuleMarkerOwner` 确认身份。
 */
export function retiredRuleBridgeManaged(content: any, kind: any): boolean {
  return kind === 'root-index' ? hasManagedRulesMarker(content) : retiredAdapterRuleManaged(content);
}

function toPosixRelative(root: any, file: any): string {
  return path.relative(path.resolve(root), path.resolve(file)).split(path.sep).join('/');
}

function readRegularFile(file: any): string | null {
  const stat = fs.lstatSync(file, { throwIfNoEntry: false });
  if (!stat || !stat.isFile() || stat.isSymbolicLink()) return null;
  return fs.readFileSync(file, 'utf8');
}

function isDirectory(directory: any): boolean {
  const stat = fs.lstatSync(directory, { throwIfNoEntry: false });
  return Boolean(stat && stat.isDirectory() && !stat.isSymbolicLink());
}

function listEntries(directory: any): any[] {
  if (!isDirectory(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true });
}

/** 收集目录下的全部非目录条目（含符号链接：符号链接必须计入未知条目）。 */
function collectProjectionEntries(directory: any): string[] {
  const entries: string[] = [];
  for (const entry of listEntries(directory)) {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory() && !entry.isSymbolicLink()) entries.push(...collectProjectionEntries(file));
    else entries.push(file);
  }
  return entries;
}

function collectManagedRuleDirectories(targetRoot: any): string[] {
  const directories: string[] = [];
  const walk = (directory: any) => {
    directories.push(directory);
    for (const entry of listEntries(directory)) {
      if (!entry.isDirectory() || entry.isSymbolicLink()) continue;
      if (RETIRED_DISCOVERY_EXCLUDED.has(entry.name)) continue;
      walk(path.join(directory, entry.name));
    }
  };
  walk(path.resolve(targetRoot));
  return directories;
}

/**
 * root-index 桥是否完整属于 Buildr：标记位于首行，且除标题、固定说明行与规则索引
 * 链接外没有其他内容。任何多余内容都视为用户内容与受管内容共存，无法安全分离。
 */
function inspectRootIndexBridge(content: any, ownerId: any): any {
  const lines = content.split('\n');
  const marker = ROOT_INDEX_MARKER_PATTERN.exec(lines[0] ?? '');
  if (!marker) return { separable: false, reason: '受管标记不在首行，无法确认整份文件属于 Buildr' };
  if (marker[1] !== ownerId) return { separable: false, ownerId: marker[1], reason: `受管标记属于 ${marker[1]}` };
  const unexpected = lines.slice(1).filter((line: any) => {
    if (!line.trim()) return false;
    if (line === ROOT_INDEX_BRIDGE_HEADING) return false;
    if (ROOT_INDEX_BRIDGE_GUIDANCE.includes(line)) return false;
    return !ROOT_INDEX_LINK_PATTERN.test(line);
  });
  if (unexpected.length) return { separable: false, ownerId, reason: `受管桥之外还有 ${unexpected.length} 行用户内容` };
  return { separable: true, ownerId, reason: null };
}

/**
 * 清理规则桥时允许回收的空目录上界：品牌根（例如 `<dir>/.cursor`、`<root>/.qoder`）。
 * root-index 桥位于工作区根，不回收任何父目录，避免误删空目录。
 */
function bridgePruneRoot(base: any, relative: any): string | null {
  const segments = relative.split(path.sep);
  if (segments.length < 2) return null;
  return path.join(path.resolve(base), segments[0]);
}

/** 列出仍存在的退役规则桥，并说明是否可安全分离。 */
export function listRetiredRuleBridgeTargets(targetRoot: any): any[] {
  const root = path.resolve(targetRoot);
  const found: any[] = [];
  const directories = collectManagedRuleDirectories(root);
  for (const adapter of RETIRED_RUNTIME_ADAPTERS) {
    for (const bridge of adapter.bridges) {
      if (bridge.kind === 'per-source') {
        for (const directory of directories) {
          const targetFile = path.join(directory, bridge.relative);
          const content = readRegularFile(targetFile);
          if (content === null || retiredAdapterRuleMarkerOwner(content) !== adapter.id) continue;
          found.push({ adapterId: adapter.id, kind: bridge.kind, targetFile, pruneEmptyRoot: bridgePruneRoot(directory, bridge.relative), separable: true, reason: null });
        }
        continue;
      }
      if (bridge.kind === 'workspace-directory') {
        for (const entry of listEntries(path.join(root, bridge.relative))) {
          if (!entry.isFile() || entry.isSymbolicLink() || !entry.name.endsWith('.md')) continue;
          const targetFile = path.join(root, bridge.relative, entry.name);
          const content = readRegularFile(targetFile);
          if (content === null || retiredAdapterRuleMarkerOwner(content) !== adapter.id) continue;
          found.push({ adapterId: adapter.id, kind: bridge.kind, targetFile, pruneEmptyRoot: bridgePruneRoot(root, bridge.relative), separable: true, reason: null });
        }
        continue;
      }
      const targetFile = path.join(root, bridge.relative);
      const content = readRegularFile(targetFile);
      if (content === null || !retiredRuleBridgeManaged(content, bridge.kind)) continue;
      const inspected = inspectRootIndexBridge(content, adapter.id);
      // 标记属于其他 adapter 的 root-index 桥不是退役投射，保持不动。
      if (!inspected.separable && inspected.ownerId !== adapter.id) continue;
      found.push({ adapterId: adapter.id, kind: bridge.kind, targetFile, pruneEmptyRoot: null, separable: inspected.separable, reason: inspected.reason });
    }
  }
  return found.sort((left: any, right: any) => left.targetFile.localeCompare(right.targetFile));
}

function retiredAdapterNamespaceRoot(targetRoot: any, adapterId: any): string {
  return path.join(path.resolve(targetRoot), ...PROJECTION_NAMESPACE_SEGMENTS, adapterId);
}

function retiredAdapterReceiptDirectories(targetRoot: any, adapter: any): any[] {
  const skillsRoot = path.join(path.resolve(targetRoot), adapter.skills.root);
  return [
    {
      directory: path.join(retiredAdapterNamespaceRoot(targetRoot, adapter.id), SKILL_PROJECTION_OWNERSHIP_RECEIPTS_DIRECTORY),
      pruneEmptyRoot: retiredAdapterNamespaceRoot(targetRoot, adapter.id),
    },
    {
      directory: path.join(skillsRoot, 'buildr', 'skill-projection-receipts', adapter.id),
      pruneEmptyRoot: path.join(skillsRoot, 'buildr'),
    },
  ];
}

function collectReceiptFiles(directory: any): string[] {
  return collectProjectionEntries(directory).filter((file: any) => file.endsWith('.json')).sort();
}

function retainedFinding(targetRoot: any, adapterId: any, targetFile: any, reason: any): any {
  return {
    status: 'warning',
    code: RETIRED_PROJECTION_RETAINED_CODE,
    adapterId,
    path: toPosixRelative(targetRoot, targetFile),
    message: `退役适配器 ${adapterId} 的既有投射无法证明所有权，已保留 ${toPosixRelative(targetRoot, targetFile)}：${reason}`,
    reason,
    userActionRequired: false,
    suggestion: '确认该路径不属于 Buildr 时手动删除；Buildr 不猜测所有权，也不会静默删除。',
  };
}

function conflictFinding(targetRoot: any, adapterId: any, targetFile: any, reason: any): any {
  return {
    status: 'conflict',
    code: RETIRED_PROJECTION_CONFLICT_CODE,
    adapterId,
    path: toPosixRelative(targetRoot, targetFile),
    message: `退役适配器 ${adapterId} 的投射与用户内容无法安全分离，整组零写入：${toPosixRelative(targetRoot, targetFile)}（${reason}）`,
    reason,
    userActionRequired: true,
    suggestion: '把用户内容移出该路径后重新运行，或确认后手动删除 Buildr 受管部分。',
  };
}

function planRetiredRuleBridgeRemovals(targetRoot: any, bridges: any[], removals: any[], findings: any[]): void {
  for (const bridge of bridges) {
    if (!bridge.separable) {
      findings.push(conflictFinding(targetRoot, bridge.adapterId, bridge.targetFile, bridge.reason || '无法安全分离'));
      continue;
    }
    const pruneEmptyRoot = bridge.pruneEmptyRoot;
    removals.push({
      type: 'file',
      targetFile: bridge.targetFile,
      expectedIntegrity: sha256Integrity(fs.readFileSync(bridge.targetFile)),
      ...(pruneEmptyRoot ? { pruneEmptyRoot } : {}),
      kind: 'retired-rules-bridge',
      source: `Retired ${bridge.adapterId} rules bridge`,
    });
  }
}

function planRetiredSkillMirrorRemovals(targetRoot: any, adapter: any, removals: any[], findings: any[]): void {
  if (adapter.skills.sharedSkillsRoot) return;
  const skillsRoot = path.join(path.resolve(targetRoot), adapter.skills.root);
  const skillsDirectory = path.join(skillsRoot, 'skills');
  // 共享技能根由标准适配器拥有：这类命名空间只报告，不删除。
  const coveredPrefixes = new Set<string>();
  for (const source of retiredAdapterReceiptDirectories(targetRoot, adapter)) {
    for (const receiptFile of collectReceiptFiles(source.directory)) {
      let receipt;
      try {
        receipt = parseSkillProjectionReceipt(fs.readFileSync(receiptFile, 'utf8'), toPosixRelative(targetRoot, receiptFile));
      } catch (error: any) {
        findings.push(retainedFinding(targetRoot, adapter.id, receiptFile, `回执无效：${error.message}`));
        continue;
      }
      if (receipt.adapterId !== adapter.id) {
        findings.push(retainedFinding(targetRoot, adapter.id, receiptFile, `回执来源身份为 ${receipt.adapterId}，与 ${adapter.id} 不一致`));
        continue;
      }
      if (receipt.schemaVersion !== 'buildr.skill-projection/v2') {
        findings.push(retainedFinding(targetRoot, adapter.id, receiptFile, `回执 schema 为 ${receipt.schemaVersion}，缺少逐文件证明`));
        continue;
      }
      if (receipt.destination !== 'workspace') {
        findings.push(retainedFinding(targetRoot, adapter.id, receiptFile, `回执 destination 为 ${receipt.destination}，不在工作区退役范围`));
        continue;
      }
      const targetDir = path.join(skillsDirectory, ...receipt.runtimePath.split('/'));
      const receiptRemoval = {
        type: 'file',
        targetFile: receiptFile,
        expectedIntegrity: sha256Integrity(fs.readFileSync(receiptFile)),
        pruneEmptyRoot: source.pruneEmptyRoot,
        kind: 'skill-projection-retirement-receipt',
        removeLast: true,
        source: `Retired ${adapter.id} Skill projection receipt ${receipt.runtimePath}`,
      };
      if (!isDirectory(targetDir)) {
        // 镜像文件已不存在，回执本身仍可证明属于 Buildr。
        removals.push(receiptRemoval);
        continue;
      }
      coveredPrefixes.add(receipt.runtimePath.split('/')[0]);
      const expectedByPath: any = new Map(receipt.files.map((file: any) => [file.path, file]));
      const actual = collectProjectionEntries(targetDir);
      const unknown = actual.filter((file: any) => !expectedByPath.has(toPosixRelative(targetDir, file)));
      const modified = actual.filter((file: any) => {
        const expected: any = expectedByPath.get(toPosixRelative(targetDir, file));
        return expected && !runtimeFileMatches(file, expected.integrity, expected.executable);
      });
      if (unknown.length || modified.length) {
        const reasons = [
          unknown.length ? `含 ${unknown.length} 个回执未登记的额外条目（${unknown.map((file: any) => toPosixRelative(targetDir, file)).join(', ')}）` : '',
          modified.length ? `受管文件已被修改（${modified.map((file: any) => toPosixRelative(targetDir, file)).join(', ')}）` : '',
        ].filter(Boolean).join('；');
        findings.push(retainedFinding(targetRoot, adapter.id, targetDir, reasons));
        continue;
      }
      if (!expectedByPath.has('SKILL.md')) {
        findings.push(retainedFinding(targetRoot, adapter.id, targetDir, '回执缺少 SKILL.md 证明'));
        continue;
      }
      for (const [relative, expected] of expectedByPath) {
        const file = path.join(targetDir, ...relative.split('/'));
        if (!fs.existsSync(file)) continue;
        removals.push({
          type: 'file',
          targetFile: file,
          expectedIntegrity: expected.integrity,
          expectedExecutable: expected.executable,
          pruneEmptyRoot: skillsRoot,
          kind: 'skill-projection-retirement-file',
          source: `Retired ${adapter.id} Skill projection ${receipt.runtimePath}`,
        });
      }
      removals.push(receiptRemoval);
    }
  }
  for (const entry of listEntries(skillsDirectory)) {
    if (!entry.isDirectory() || entry.isSymbolicLink()) continue;
    if (coveredPrefixes.has(entry.name)) continue;
    if (!fs.existsSync(path.join(skillsDirectory, entry.name, 'SKILL.md'))) continue;
    findings.push(retainedFinding(targetRoot, adapter.id, path.join(skillsDirectory, entry.name), '缺少完整所有权回执'));
  }
}

/** 共享技能根命名空间只报告不删除：其回执与文件由标准适配器拥有。 */
function reportSharedRootNamespace(targetRoot: any, adapter: any, findings: any[]): void {
  const namespaceRoot = retiredAdapterNamespaceRoot(targetRoot, adapter.id);
  if (!fs.existsSync(namespaceRoot)) return;
  const files = collectProjectionEntries(namespaceRoot);
  if (!files.length) return;
  findings.push(retainedFinding(
    targetRoot,
    adapter.id,
    namespaceRoot,
    `技能根 ${adapter.skills.root} 由标准适配器拥有，命名空间内 ${files.length} 个文件归属需人工确认`,
  ));
}

/**
 * 退役投射的完整计划。只有标准适配器的受管全工作区操作会得到非空计划；
 * 显式选择其他适配器或局部 scope 时不触碰退役品牌的投射。
 */
export function buildRetiredRuntimeProjectionPlan(options: any = {}): any {
  const targetRoot = path.resolve(options.targetRoot ?? '.');
  const scope = options.scope ?? '.';
  const adapterId = options.adapterId ?? null;
  const empty = { removals: [], findings: [], retained: [], adapters: [], sharedRootAdapters: [] as string[] };
  if (adapterId !== 'agents-standard' || scope !== '.') return empty;
  if (!fs.existsSync(targetRoot)) return empty;
  const removals: any[] = [];
  const findings: any[] = [];
  planRetiredRuleBridgeRemovals(targetRoot, listRetiredRuleBridgeTargets(targetRoot), removals, findings);
  for (const adapter of RETIRED_RUNTIME_ADAPTERS) {
    if (adapter.skills.sharedSkillsRoot) {
      reportSharedRootNamespace(targetRoot, adapter, findings);
      continue;
    }
    planRetiredSkillMirrorRemovals(targetRoot, adapter, removals, findings);
  }
  return {
    removals,
    findings,
    retained: findings.filter((finding: any) => finding.status === 'warning'),
    adapters: retiredRuntimeAdapterIds(),
    sharedRootAdapters: RETIRED_RUNTIME_ADAPTERS.filter((adapter: any) => adapter.skills.sharedSkillsRoot).map((adapter: any) => adapter.id),
  };
}

/** doctor 报告面：仍未清理或无法证明所有权的退役投射。 */
export function retiredRuntimeProjectionFindings(targetRoot: any): any[] {
  return buildRetiredRuntimeProjectionPlan({ targetRoot, scope: '.', adapterId: 'agents-standard' }).findings;
}

/** 退役投射清单与当前观察结果，用于报告与验证。 */
export function retiredRuntimeProjectionInventory(targetRoot: any): any {
  const root = path.resolve(targetRoot);
  const bridges = listRetiredRuleBridgeTargets(root);
  return {
    schemaVersion: 'buildr.retired-runtime-projection-inventory/v1',
    adapters: RETIRED_RUNTIME_ADAPTERS.map((adapter: any) => ({
      id: adapter.id,
      skillsRoot: adapter.skills.root,
      sharedSkillsRoot: adapter.skills.sharedSkillsRoot,
      bridges: adapter.bridges.map((bridge: any) => ({ kind: bridge.kind, relative: bridge.relative.split(path.sep).join('/') })),
      namespace: toPosixRelative(root, retiredAdapterNamespaceRoot(root, adapter.id)),
    })),
    observed: {
      bridges: bridges.map((bridge: any) => ({ adapterId: bridge.adapterId, path: toPosixRelative(root, bridge.targetFile), separable: bridge.separable, reason: bridge.reason })),
      namespacePresent: RETIRED_RUNTIME_ADAPTERS.filter((adapter: any) => fs.existsSync(retiredAdapterNamespaceRoot(root, adapter.id))).map((adapter: any) => adapter.id),
    },
  };
}
